### ISSUE TITLE
Incompatibility with older version of php

### ISSUE THREAD

**Issue by hoseindoost** [asadidebuger/WPCrudRest#3]
Hi, 
Thanks for presenting this powerful tool for generating WordPress plugins. It is very interesting.
Please mention which version of PHP is required for deploying generated plugins. I'm using PHP V5.3.13, and the generated plugin did not activate on WordPress. It gives me fatal errors. Is it due to my PHP version?

**Comment by asadidebuger** [comment]
Pleas use PHP v 7 and greater...
